chore: update demo data (#7)
* Initial commit

* Example site for themes

* Adding a menu to the content example site

* Adding the hyde theme

* Adding a read me for the repository

* Adding the Herring Cove theme

* small tweak to hyde read me

* including the static directory

* Hyde theme: sync with upstream to v2.0.0.

CSS is now split into poole.css and hyde.css; chrome/sidebar.html updated.

Also cherry-pick:

  * poole/hyde@48b9d1f - Set a max-width for images

* adding archetypes to the existing themes

* themes moved to their own repos

* updated readme to reflect the new intent

* Added layouts directory to avoid error when generating site

Hugo ouputs an error like:

ERROR: 2014/11/19 Walker:  lstat /path/to/HugoBasicExample/layouts: no such file or directory

when testing a new theme against this repo, unless the layouts folder is created first

Tested with hugo built from commit master (on commit 728d0fa32cb666264045783518cc6ded5c78f246)

* Tweaked git ignore to exclude the generated public folder

* Fix minor typo; updated URLs

* Some more tweaks to README.md

* Set canonifyurls = true

* Add themes to .gitignore

* Add some more content

And pagination config to show pagination in the themes that support that.

* Remove themeSite specific params from config

* Update links in README due to the org transition

* Fix typo in command to clone hugoBasicExample

* Remove some outdated info

* Update about.md

* Fix minor typos and update copyright year

* Add install instructions for single theme in README.md

Fixed #12

* Add Series Taxonomy (#19)

Closes #18

* Added french posts translation for testing internationalization (i18n) (#11)

* Revert "Add Series Taxonomy (#19)" (#22)

This reverts commit 4e47e94a69eb67a37f0dd55a2b4eaad05bb8ffe3.

A [great number](https://app.netlify.com/sites/hugothemes/deploys/5c6936d1dddaef000819a6e8) of theme demos on the website broke because of this commit due to the following:

- Series is on the predefined frontmatter variable lists due to its use in the internal opengraph template.
- Series is predefined as an array whereas I entered it as a string.
- Also series needs to be defined as a Taxonomy in the config of an exampleSite. Since the config is inherited by theme authors if they have not defined the series taxonomy then their demo will again break.

**NOTE**
I will be more rigorous with testing before sending more PRs.

cc: @digitalcraftsman

* Disable French (#21)

Commit 93a7b4c had the side effect of causing existing theme demos that rely on the HugoBasicExample to display the French language posts.

So with this PR the French translation of the posts is disabled by default, to keep things for existing demos as before.

**NOTE**
When we are done with overhauling the HugoBasicExample we will need to add documentation in its README. 

For example in this case we will need to state that authors who wish to have a multilingual theme demo will need to remove `disableLanguages = ["fr"]` from the exampleSite config.

* Re-add Series Taxonomy with 2nd config (#23)

* Add posts symlink (#24)

Some themes like for example [Hyde Hyde](https://github.com/htr3n/hyde-hyde/tree/master/exampleSite/content) have their content files under a section called `posts` 

Currently the index page of these theme demos renders empty because there is no `posts` section in the HugoBasicExample.

So to fix this I have added a symlink called `posts` that points to the content files located under the `post` of the HugoBasicExample repo.

In theory this workaround can be used for other sections as well like e.g. `articles` etc (as long as it doesn't break anything).

* Move menu configuration in config.toml (#25)

* Remove SymLink Add Aliases (#26)

This PR reverts commit 6ad74b6 and instead adds the following under `content/post/_index.md`:
```
aliases = ["posts","articles"]
```

Basically the symlink from #24 duplicated all posts in theme demos, so it needs to be removed.

Aliases on the other hand thanks to the Netlify Redirect Output Format defined in the gohugoio theme over [here](https://github.com/gohugoio/hugoThemesSite/blob/4320e757c9f8fce5e265c725bd1e9bd061f70753/config.toml#L21-L31) and [here](https://github.com/gohugoio/gohugoioTheme/blob/master/layouts/index.redir) become 301 redirects, so they hopefully offer a solution to the issue of the various themes using different sections in their demos that I described in https://github.com/gohugoio/hugoBasicExample/pull/24

* Add more Taxonomies configuration (#27)

This PR adds the default Hugo taxonomies configuration in the second config of the HugoBasicExample.

This PR will fix a number of theme demos that currently require the default Hugo taxonomies.

For example the [Plain Blog](https://themes.gohugo.io/plain-blog/) theme demo will generate once again after this PR is merged.

* Move About menu item to config (#28)

This should fix the About menu item duplication in various theme demos like in [this one](https://themes.gohugo.io//theme/hermit/)

* Add more Aliases (#29)

* Disable French (#30)

* Add Posts Type (#31)

This PR adds a `type = "posts"` for themes that need it. 

Most notably [Hyde Hyde](https://themes.gohugo.io/theme/hyde-hyde/) that currently has its index page empty will have it populated with posts once again.

If more themes need different content types I will see whether it is possible to turn `type` into an array to add more of these.

* Update Content (#33)

* Revert author parameter back to a string (#36)

This reverts the author front matter parameter back to a string in order to fix the 12 theme demos that broke with #33 

The demos that were supposed to be fixed in that PR were whiteListed with https://github.com/gohugoio/hugoThemes/pull/586

* Assign multiple content types (#37)

* Refactor HugoBasicExample (#42)

* Fixes (#43)

This PR fixes the issues that have arisen with #42 and it needs to be merged before https://github.com/gohugoio/hugoThemes/pull/600

* Update HugoBasicExample Content (#45)

Closes #7 , closes #9 

The existing outdated Hugo documentation in this repo will be replaced with the following more-or-less *evergreen* content:

- **Markdown & HTML Syntax Guide** shows whether a theme has decorated basic HTML elements with CSS. Note that I have not included the Markdown syntax for aligning table columns due to: https://github.com/russross/blackfriday/issues/506

- **Rich Content** features a brief showcase of Hugo’s Privacy config and related Simple shortcodes. Note that I have chosen to embed content that showcases typography by several designers in various media including a 360° interactive YouTube video (for inspiration). Also these embeds should be covered under [Fair Use](https://fairuse.stanford.edu/overview/fair-use/what-is-fair-use/) since these are meant for teaching users how these Hugo shortcodes work.

- **Placeholder Content** includes dummy copy along with a diagram and a link with info about the *Van de Graaf Canon* for constructing layouts (that can also be applied to websites). Note: the diagram is Open Source and taken from https://en.wikipedia.org/wiki/Canons_of_page_construction#Van_de_Graaf_canon (there is a link to this page in the caption).

- **Math Typesetting** a brief tutorial about enabling KaTeX in Hugo (the Hugo Docs mention MathJax which is slower)

- **Emoji Support** brief tutorial about Hugo’s built-in Unicode emoji support (as mentioned in the Hugo Docs) but also this includes an original technique for enabling non Unicode emoji in Hugo by using Static Image Replacement with the `replaceRE` function. Note: custom icons are from the Open Source [Mutant Standard](https://mutant.tech) emoji set.

Also note that the **About** Page has been expanded and updated to reflect Hugo’s current features.

---

**NOTES**

Besides quoting from the Hugo Docs (when needed), these content files contain original content written and curated by me and whatever sources I used were modified  to such an extent that there is no need for footnotes.

The author credit for the new content is Hugo Authors since this is meant for the Hugo community -of which I am a current member- furthermore the content also may be modified by someone else in the future, so this credit seems more appropriate than one with my name.

P.S. @digitalcraftsman I have not included a guide about Modular Typography as this would have been quite involved and I am running out of time.

P.S.2 This PR also fixes the path of the `menu.main` `/about/` item see: #41 by @guylyons

* Remove outdated content (#46)

For some reason the old content was not deleted when #45 was merged.

So I am sending this one to have it removed.

cc: @digitalcraftsman

* Corretions

* Move image in sample post further demo

This prevents the image from appearing as part of the preview / summary
of this content file.

* Add Docs alias (#48)

This is needed for this theme submission: https://github.com/gohugoio/hugoThemes/issues/605

* Minor Corrections (#49)

* Remove first headline from post

.Summary contains the headline rendered as <h2> tag which can break the layout of post listings in which the summary is used.

* Refactor and simplify (#53)

* Cleanup repo (#54)

* Update README.md (#55)

This closes #38 

This re-write aims to provide some instructions for this repo to theme authors and other users.

* Add timeout (#56)

* Remove backslash at the end of baseURL

Also see: https://github.com/gohugoio/hugoThemesSite/issues/72

* Mention goldmark instead of blackfriday

* Add alias

* Add archives content file

Also this reverts the previous commit

* Remove mmark

* Upgrade KaTex + workaround for Inline Math

For an equation to render inline make sure to wrap it within an inline shortcode so that the Markdown processor is not used for parsing.

Also note that for inline KaTex since `katex@0.11.1` use the `\( ... \)` delimiters and not the `$` sign.

Closes: #60

* Fix nested list example

* Project and Content Cleanup, Normalization (#61)

* Update markdown-syntax.md

* Fix the link of Built-in Shortcodes (#66)

* Remove instagram shortcode from example content

Otherwise it causes build failures. See https://github.com/gohugoio/hugo/issues/7866

* Ignore getJSON errors to prevent build failures

* Fix typo (#67)

Co-authored-by: Steve Francia <steve.francia@gmail.com>
Co-authored-by: Dato Simó <dato@net.com.org.es>
Co-authored-by: Rasmus Stougaard <rasmus.stougaard@gmail.com>
Co-authored-by: Anthony Fok <foka@debian.org>
Co-authored-by: bep <bjorn.erik.pedersen@gmail.com>
Co-authored-by: digitalcraftsman <digitalcraftsman@users.noreply.github.com>
Co-authored-by: attwad <attwad@users.noreply.github.com>
Co-authored-by: Hanzei <Hanzei@users.noreply.github.com>
Co-authored-by: Alexandros <onedrawingperday@users.noreply.github.com>
Co-authored-by: Rémy Jacquin <1536771+remyj38@users.noreply.github.com>
Co-authored-by: Alex <onedrawingperday@gmail.com>
Co-authored-by: Digitalcraftsman <digitalcraftsman@protonmail.com>
Co-authored-by: Jhaura Wachsman <jw@jhaurawachsman.com>
Co-authored-by: Razon Yang <razonyang@gmail.com>
Co-authored-by: Cody Brownstein <25962175+cbrownstein@users.noreply.github.com>